'use client'

import { useState, useTransition } from 'react'
import { useSearchParams } from 'next/navigation'
import { useTranslations } from 'next-intl'
import { Bookmark, Loader2 } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { saveSavedSearch } from '@/modules/cabinet/actions'
import { canonicalizeFilters } from '@/modules/listings/lib/savedSearchCanonicalize'

export function SaveSearchButton() {
  const t = useTranslations('saved_search')
  const searchParams = useSearchParams()
  const [open, setOpen] = useState(false)
  const [name, setName] = useState('')
  const [isPending, startTransition] = useTransition()

  // Build autogenerated name from active filters
  function buildAutoName(): string {
    const filters = canonicalizeFilters(searchParams)
    const parts: string[] = []
    if (filters.listingType) parts.push(filters.listingType)
    if (filters.propertyType) parts.push(filters.propertyType)
    if (filters.priceMin || filters.priceMax) {
      const from = filters.priceMin ? String(filters.priceMin) : ''
      const to = filters.priceMax ? String(filters.priceMax) : ''
      parts.push(from && to ? `${from}–${to}` : from ? `>${from}` : `<${to}`)
    }
    if (filters.rooms?.length) parts.push(`${filters.rooms.join('+')}+`)
    return parts.join(', ') || t('filter_summary')
  }

  function handleSave() {
    const finalName = name.trim() || buildAutoName()
    // Convert URLSearchParams to plain Record for the server action
    const rawParams: Record<string, string | string[]> = {}
    searchParams.forEach((value, key) => {
      const existing = rawParams[key]
      if (existing) {
        rawParams[key] = Array.isArray(existing) ? [...existing, value] : [existing, value]
      } else {
        rawParams[key] = value
      }
    })

    startTransition(async () => {
      const result = await saveSavedSearch(rawParams, finalName)
      if (result.code === 'already_exists') {
        toast.info(t('already_saved'))
        setOpen(false)
        return
      }
      if (result.error) {
        toast.error(result.error)
        return
      }
      toast.success(t('save_success'))
      setOpen(false)
      setName('')
    })
  }

  return (
    <>
      <Button
        variant="outline"
        size="lg"
        className="gap-1.5 rounded-xl"
        onClick={() => setOpen(true)}
      >
        <Bookmark className="h-4 w-4 shrink-0" />
        <span className="hidden sm:inline">{t('save_action')}</span>
      </Button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="w-80 max-w-[calc(100vw-2rem)]">
          <DialogHeader>
            <DialogTitle className="text-sm font-semibold">{t('save_modal_title')}</DialogTitle>
          </DialogHeader>
          <div className="flex flex-col gap-3">
            <div className="flex flex-col gap-1.5">
              <Label className="text-xs text-muted-foreground">{t('name_placeholder')}</Label>
              <Input
                value={name}
                onChange={e => setName(e.target.value)}
                placeholder={buildAutoName()}
                className="h-9 rounded-xl text-sm"
                maxLength={80}
                onKeyDown={e => { if (e.key === 'Enter') handleSave() }}
                autoFocus
              />
            </div>
            <div className="flex flex-col sm:flex-row sm:justify-end gap-2">
              <Button variant="ghost" size="sm" onClick={() => setOpen(false)} disabled={isPending}>
                {t('cancel')}
              </Button>
              <Button size="sm" onClick={handleSave} disabled={isPending} className="gap-1.5">
                {isPending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Bookmark className="h-3.5 w-3.5 shrink-0" />}
                {t('save')}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}
