'use client'

import { useState, useTransition } from 'react'
import { useSearchParams } from 'next/navigation'
import { useTranslations } from 'next-intl'
import { Bookmark } from 'lucide-react'
import { Box, Button, Flex, Loader, TextInput } from '@mantine/core'
import { toast } from '@/lib/toast'
import { MantineModal } from '@/design-system/mantine/patterns'
import { saveSavedSearch } from '@/modules/cabinet/actions'
import { canonicalizeFilters } from '@/modules/listings/lib/savedSearchCanonicalize'

const FULL_BELOW_SM = { base: '100%', sm: 'auto' } as const

export function SaveSearchButton() {
  const t = useTranslations('saved_search')
  const searchParams = useSearchParams()
  const [open, setOpen] = useState(false)
  const [name, setName] = useState('')
  const [isPending, startTransition] = useTransition()

  // Build autogenerated name from active filters
  function buildAutoName(): string {
    const filters = canonicalizeFilters(searchParams)
    const parts: string[] = []
    if (filters.listingType) parts.push(filters.listingType)
    if (filters.propertyType) parts.push(filters.propertyType)
    if (filters.priceMin || filters.priceMax) {
      const from = filters.priceMin ? String(filters.priceMin) : ''
      const to = filters.priceMax ? String(filters.priceMax) : ''
      parts.push(from && to ? `${from}–${to}` : from ? `>${from}` : `<${to}`)
    }
    if (filters.rooms?.length) parts.push(`${filters.rooms.join('+')}+`)
    return parts.join(', ') || t('filter_summary')
  }

  function handleSave() {
    const finalName = name.trim() || buildAutoName()
    // Convert URLSearchParams to plain Record for the server action
    const rawParams: Record<string, string | string[]> = {}
    searchParams.forEach((value, key) => {
      const existing = rawParams[key]
      if (existing) {
        rawParams[key] = Array.isArray(existing) ? [...existing, value] : [existing, value]
      } else {
        rawParams[key] = value
      }
    })

    startTransition(async () => {
      const result = await saveSavedSearch(rawParams, finalName)
      if (result.code === 'already_exists') {
        toast.info(t('already_saved'))
        setOpen(false)
        return
      }
      if (result.error) {
        toast.error(result.error)
        return
      }
      toast.success(t('save_success'))
      setOpen(false)
      setName('')
    })
  }

  return (
    <>
      <Button
        variant="default"
        w={{ base: '100%', sm: 'auto' }}
        leftSection={<Bookmark size={16} />}
        onClick={() => setOpen(true)}
      >
        <Box component="span" visibleFrom="sm">{t('save_action')}</Box>
      </Button>

      <MantineModal
        opened={open}
        onClose={() => setOpen(false)}
        title={t('save_modal_title')}
        footer={
          <Flex direction={{ base: 'column-reverse', sm: 'row' }} justify={{ sm: 'flex-end' }} gap="xs">
            <Button variant="subtle" color="gray" w={FULL_BELOW_SM} onClick={() => setOpen(false)} disabled={isPending}>
              {t('cancel')}
            </Button>
            <Button
              w={FULL_BELOW_SM}
              onClick={handleSave}
              disabled={isPending}
              leftSection={isPending ? <Loader size={14} color="white" /> : <Bookmark size={14} />}
            >
              {t('save')}
            </Button>
          </Flex>
        }
      >
        <TextInput
          label={t('name_placeholder')}
          value={name}
          onChange={e => setName(e.target.value)}
          placeholder={buildAutoName()}
          maxLength={80}
          onKeyDown={e => { if (e.key === 'Enter') handleSave() }}
          autoFocus
        />
      </MantineModal>
    </>
  )
}
