-- schema-drift-check.sql
-- Generated 2026-05-22T19:19:45.875Z by: npm run check:schema-drift
-- Run in Supabase SQL Editor. Read-only — does not modify any data.
--
-- Interface → table mapping covered:
--   User                 → users                    (29 cols)
--   UserChangeLog        → user_change_log          (7 cols)
--   UserStatusHistory    → user_status_history      (7 cols)
--   EmailChangeToken     → email_change_tokens      (7 cols)
--   EmailTemplate        → email_templates          (10 cols)
--   Location             → locations                (12 cols)
--   Listing              → listings                 (39 cols)
--   ListingImage         → listing_images           (5 cols)
--   Favorite             → favorites                (4 cols)
--   FavoritePriceAlert   → favorite_price_alerts    (4 cols)
--   SavedSearch          → saved_searches           (12 cols)
--   ListingReport        → listing_reports          (7 cols)
--   ReportAction         → report_actions           (8 cols)
--   SupportTicket        → support_tickets          (11 cols)
--   SupportTicketEvent   → support_ticket_events    (9 cols)
--   Notification         → notifications            (8 cols)
--   DBCurrency           → currencies               (12 cols)
--   DBExchangeProvider   → exchange_providers       (11 cols)
--   DBPropertyType       → property_types           (10 cols)
--   Page                 → pages                    (7 cols)
--   SiteSetting          → site_settings            (3 cols)
--   Company              → companies                (4 cols)
--   Collection           → collections              (5 cols)
--   CollectionItem       → collection_items         (3 cols)
--   RecentlyViewed       → recently_viewed          (4 cols)
--   RolePermission       → role_permissions         (4 cols)
--   ContactInquiry       → contact_inquiries        (14 cols)
--   ContactInquiryReply  → contact_inquiry_replies  (5 cols)
--
-- To regenerate after any change to src/types/database.ts:
--   npm run check:schema-drift

-- ═══════════════════════════════════════════════════════════════════════════
-- RESULT SET 1: columns EXPECTED by TypeScript types but MISSING in live DB
--   → each row here is a potential PGRST204 runtime error on write
-- ═══════════════════════════════════════════════════════════════════════════

WITH expected(table_name, column_name) AS (
  VALUES
    ('users', 'id'),
    ('users', 'public_id'),
    ('users', 'name'),
    ('users', 'last_name'),
    ('users', 'phone'),
    ('users', 'whatsapp'),
    ('users', 'avatar_url'),
    ('users', 'role'),
    ('users', 'user_type'),
    ('users', 'status'),
    ('users', 'block_reason'),
    ('users', 'suspended_until'),
    ('users', 'company_name'),
    ('users', 'company_logo_url'),
    ('users', 'company_id'),
    ('users', 'website'),
    ('users', 'is_verified'),
    ('users', 'social_provider'),
    ('users', 'location_id'),
    ('users', 'position'),
    ('users', 'year_started'),
    ('users', 'deleted_at'),
    ('users', 'location_request'),
    ('users', 'preferred_currency'),
    ('users', 'pending_email'),
    ('users', 'last_seen_at'),
    ('users', 'inactivity_warning_sent_at'),
    ('users', 'preferred_locale'),
    ('users', 'created_at'),
    ('user_change_log', 'id'),
    ('user_change_log', 'user_id'),
    ('user_change_log', 'changed_by'),
    ('user_change_log', 'field_name'),
    ('user_change_log', 'old_value'),
    ('user_change_log', 'new_value'),
    ('user_change_log', 'changed_at'),
    ('user_status_history', 'id'),
    ('user_status_history', 'user_id'),
    ('user_status_history', 'old_status'),
    ('user_status_history', 'new_status'),
    ('user_status_history', 'reason'),
    ('user_status_history', 'changed_by'),
    ('user_status_history', 'changed_at'),
    ('email_change_tokens', 'id'),
    ('email_change_tokens', 'user_id'),
    ('email_change_tokens', 'new_email'),
    ('email_change_tokens', 'token_hash'),
    ('email_change_tokens', 'expires_at'),
    ('email_change_tokens', 'consumed_at'),
    ('email_change_tokens', 'created_at'),
    ('email_templates', 'id'),
    ('email_templates', 'key'),
    ('email_templates', 'locale'),
    ('email_templates', 'subject'),
    ('email_templates', 'html_body'),
    ('email_templates', 'variables'),
    ('email_templates', 'is_active'),
    ('email_templates', 'created_at'),
    ('email_templates', 'updated_at'),
    ('email_templates', 'updated_by'),
    ('locations', 'id'),
    ('locations', 'name_al'),
    ('locations', 'name_en'),
    ('locations', 'slug'),
    ('locations', 'type'),
    ('locations', 'parent_id'),
    ('locations', 'region_id'),
    ('locations', 'lat'),
    ('locations', 'lng'),
    ('locations', 'image_url'),
    ('locations', 'is_featured'),
    ('locations', 'display_order'),
    ('listings', 'id'),
    ('listings', 'public_id'),
    ('listings', 'user_id'),
    ('listings', 'location_id'),
    ('listings', 'slug'),
    ('listings', 'title'),
    ('listings', 'description'),
    ('listings', 'price'),
    ('listings', 'price_old'),
    ('listings', 'currency'),
    ('listings', 'listing_type'),
    ('listings', 'property_type'),
    ('listings', 'condition'),
    ('listings', 'wall_type'),
    ('listings', 'heating'),
    ('listings', 'rooms'),
    ('listings', 'bedrooms'),
    ('listings', 'bathrooms'),
    ('listings', 'toilets'),
    ('listings', 'area_gross'),
    ('listings', 'area_net'),
    ('listings', 'floor'),
    ('listings', 'total_floors'),
    ('listings', 'multi_storey_building'),
    ('listings', 'land_legal_status'),
    ('listings', 'land_zoning'),
    ('listings', 'land_development_potential'),
    ('listings', 'offer_type'),
    ('listings', 'purchase_conditions'),
    ('listings', 'year_built'),
    ('listings', 'address'),
    ('listings', 'lat'),
    ('listings', 'lng'),
    ('listings', 'views_count'),
    ('listings', 'is_premium'),
    ('listings', 'status'),
    ('listings', 'expires_at'),
    ('listings', 'created_at'),
    ('listings', 'updated_at'),
    ('listing_images', 'id'),
    ('listing_images', 'listing_id'),
    ('listing_images', 'url'),
    ('listing_images', 'order'),
    ('listing_images', 'is_cover'),
    ('favorites', 'id'),
    ('favorites', 'user_id'),
    ('favorites', 'listing_id'),
    ('favorites', 'created_at'),
    ('favorite_price_alerts', 'user_id'),
    ('favorite_price_alerts', 'listing_id'),
    ('favorite_price_alerts', 'last_notified_price'),
    ('favorite_price_alerts', 'last_notified_at'),
    ('saved_searches', 'id'),
    ('saved_searches', 'user_id'),
    ('saved_searches', 'name'),
    ('saved_searches', 'filters'),
    ('saved_searches', 'filters_hash'),
    ('saved_searches', 'notify_email'),
    ('saved_searches', 'notify_frequency'),
    ('saved_searches', 'last_checked_at'),
    ('saved_searches', 'last_viewed_at'),
    ('saved_searches', 'new_count'),
    ('saved_searches', 'updated_at'),
    ('saved_searches', 'created_at'),
    ('listing_reports', 'id'),
    ('listing_reports', 'listing_id'),
    ('listing_reports', 'user_id'),
    ('listing_reports', 'reason'),
    ('listing_reports', 'comment'),
    ('listing_reports', 'status'),
    ('listing_reports', 'created_at'),
    ('report_actions', 'id'),
    ('report_actions', 'report_id'),
    ('report_actions', 'actor_id'),
    ('report_actions', 'actor_role'),
    ('report_actions', 'old_status'),
    ('report_actions', 'new_status'),
    ('report_actions', 'notes'),
    ('report_actions', 'created_at'),
    ('support_tickets', 'id'),
    ('support_tickets', 'user_id'),
    ('support_tickets', 'subject'),
    ('support_tickets', 'status'),
    ('support_tickets', 'assigned_to'),
    ('support_tickets', 'created_at'),
    ('support_tickets', 'reported_user_id'),
    ('support_tickets', 'reason'),
    ('support_tickets', 'created_by_admin_id'),
    ('support_tickets', 'ticket_type'),
    ('support_tickets', 'updated_at'),
    ('support_ticket_events', 'id'),
    ('support_ticket_events', 'ticket_id'),
    ('support_ticket_events', 'actor_user_id'),
    ('support_ticket_events', 'actor_role'),
    ('support_ticket_events', 'event_type'),
    ('support_ticket_events', 'old_status'),
    ('support_ticket_events', 'new_status'),
    ('support_ticket_events', 'note'),
    ('support_ticket_events', 'created_at'),
    ('notifications', 'id'),
    ('notifications', 'user_id'),
    ('notifications', 'type'),
    ('notifications', 'title'),
    ('notifications', 'body'),
    ('notifications', 'link'),
    ('notifications', 'is_read'),
    ('notifications', 'created_at'),
    ('currencies', 'id'),
    ('currencies', 'code'),
    ('currencies', 'symbol'),
    ('currencies', 'name_sq'),
    ('currencies', 'name_en'),
    ('currencies', 'name_uk'),
    ('currencies', 'name_it'),
    ('currencies', 'is_active'),
    ('currencies', 'is_default'),
    ('currencies', 'decimals'),
    ('currencies', 'created_at'),
    ('currencies', 'updated_at'),
    ('exchange_providers', 'id'),
    ('exchange_providers', 'name'),
    ('exchange_providers', 'endpoint_url'),
    ('exchange_providers', 'api_key'),
    ('exchange_providers', 'refresh_interval_min'),
    ('exchange_providers', 'priority'),
    ('exchange_providers', 'mode'),
    ('exchange_providers', 'is_enabled'),
    ('exchange_providers', 'notes'),
    ('exchange_providers', 'created_at'),
    ('exchange_providers', 'updated_at'),
    ('property_types', 'id'),
    ('property_types', 'slug'),
    ('property_types', 'name_sq'),
    ('property_types', 'name_en'),
    ('property_types', 'name_uk'),
    ('property_types', 'name_it'),
    ('property_types', 'is_active'),
    ('property_types', 'sort_order'),
    ('property_types', 'created_at'),
    ('property_types', 'updated_at'),
    ('pages', 'id'),
    ('pages', 'title'),
    ('pages', 'slug'),
    ('pages', 'content'),
    ('pages', 'is_published'),
    ('pages', 'updated_by'),
    ('pages', 'updated_at'),
    ('site_settings', 'key'),
    ('site_settings', 'value'),
    ('site_settings', 'updated_at'),
    ('companies', 'id'),
    ('companies', 'name'),
    ('companies', 'logo_url'),
    ('companies', 'created_at'),
    ('collections', 'id'),
    ('collections', 'user_id'),
    ('collections', 'name'),
    ('collections', 'created_at'),
    ('collections', 'updated_at'),
    ('collection_items', 'collection_id'),
    ('collection_items', 'listing_id'),
    ('collection_items', 'created_at'),
    ('recently_viewed', 'id'),
    ('recently_viewed', 'user_id'),
    ('recently_viewed', 'listing_id'),
    ('recently_viewed', 'viewed_at'),
    ('role_permissions', 'role'),
    ('role_permissions', 'permission_key'),
    ('role_permissions', 'allowed'),
    ('role_permissions', 'updated_at'),
    ('contact_inquiries', 'id'),
    ('contact_inquiries', 'created_at'),
    ('contact_inquiries', 'topic'),
    ('contact_inquiries', 'custom_subject'),
    ('contact_inquiries', 'name'),
    ('contact_inquiries', 'email'),
    ('contact_inquiries', 'message'),
    ('contact_inquiries', 'target_mailbox'),
    ('contact_inquiries', 'requester_ip'),
    ('contact_inquiries', 'status'),
    ('contact_inquiries', 'handled_by'),
    ('contact_inquiries', 'handled_at'),
    ('contact_inquiries', 'reply_count'),
    ('contact_inquiry_replies', 'id'),
    ('contact_inquiry_replies', 'inquiry_id'),
    ('contact_inquiry_replies', 'replied_by'),
    ('contact_inquiry_replies', 'body'),
    ('contact_inquiry_replies', 'created_at')
)
SELECT
  e.table_name,
  e.column_name,
  'missing in DB' AS status
FROM expected e
LEFT JOIN information_schema.columns ic
  ON  ic.table_schema = 'public'
  AND ic.table_name   = e.table_name
  AND ic.column_name  = e.column_name
WHERE ic.column_name IS NULL
ORDER BY e.table_name, e.column_name;


-- ═══════════════════════════════════════════════════════════════════════════
-- RESULT SET 2 (informational): DB columns ABSENT from TypeScript types
--   → may be intentional (DB internals, deprecated cols, audit triggers, etc.)
-- ═══════════════════════════════════════════════════════════════════════════

WITH expected(table_name, column_name) AS (
  VALUES
    ('users', 'id'),
    ('users', 'public_id'),
    ('users', 'name'),
    ('users', 'last_name'),
    ('users', 'phone'),
    ('users', 'whatsapp'),
    ('users', 'avatar_url'),
    ('users', 'role'),
    ('users', 'user_type'),
    ('users', 'status'),
    ('users', 'block_reason'),
    ('users', 'suspended_until'),
    ('users', 'company_name'),
    ('users', 'company_logo_url'),
    ('users', 'company_id'),
    ('users', 'website'),
    ('users', 'is_verified'),
    ('users', 'social_provider'),
    ('users', 'location_id'),
    ('users', 'position'),
    ('users', 'year_started'),
    ('users', 'deleted_at'),
    ('users', 'location_request'),
    ('users', 'preferred_currency'),
    ('users', 'pending_email'),
    ('users', 'last_seen_at'),
    ('users', 'inactivity_warning_sent_at'),
    ('users', 'preferred_locale'),
    ('users', 'created_at'),
    ('user_change_log', 'id'),
    ('user_change_log', 'user_id'),
    ('user_change_log', 'changed_by'),
    ('user_change_log', 'field_name'),
    ('user_change_log', 'old_value'),
    ('user_change_log', 'new_value'),
    ('user_change_log', 'changed_at'),
    ('user_status_history', 'id'),
    ('user_status_history', 'user_id'),
    ('user_status_history', 'old_status'),
    ('user_status_history', 'new_status'),
    ('user_status_history', 'reason'),
    ('user_status_history', 'changed_by'),
    ('user_status_history', 'changed_at'),
    ('email_change_tokens', 'id'),
    ('email_change_tokens', 'user_id'),
    ('email_change_tokens', 'new_email'),
    ('email_change_tokens', 'token_hash'),
    ('email_change_tokens', 'expires_at'),
    ('email_change_tokens', 'consumed_at'),
    ('email_change_tokens', 'created_at'),
    ('email_templates', 'id'),
    ('email_templates', 'key'),
    ('email_templates', 'locale'),
    ('email_templates', 'subject'),
    ('email_templates', 'html_body'),
    ('email_templates', 'variables'),
    ('email_templates', 'is_active'),
    ('email_templates', 'created_at'),
    ('email_templates', 'updated_at'),
    ('email_templates', 'updated_by'),
    ('locations', 'id'),
    ('locations', 'name_al'),
    ('locations', 'name_en'),
    ('locations', 'slug'),
    ('locations', 'type'),
    ('locations', 'parent_id'),
    ('locations', 'region_id'),
    ('locations', 'lat'),
    ('locations', 'lng'),
    ('locations', 'image_url'),
    ('locations', 'is_featured'),
    ('locations', 'display_order'),
    ('listings', 'id'),
    ('listings', 'public_id'),
    ('listings', 'user_id'),
    ('listings', 'location_id'),
    ('listings', 'slug'),
    ('listings', 'title'),
    ('listings', 'description'),
    ('listings', 'price'),
    ('listings', 'price_old'),
    ('listings', 'currency'),
    ('listings', 'listing_type'),
    ('listings', 'property_type'),
    ('listings', 'condition'),
    ('listings', 'wall_type'),
    ('listings', 'heating'),
    ('listings', 'rooms'),
    ('listings', 'bedrooms'),
    ('listings', 'bathrooms'),
    ('listings', 'toilets'),
    ('listings', 'area_gross'),
    ('listings', 'area_net'),
    ('listings', 'floor'),
    ('listings', 'total_floors'),
    ('listings', 'multi_storey_building'),
    ('listings', 'land_legal_status'),
    ('listings', 'land_zoning'),
    ('listings', 'land_development_potential'),
    ('listings', 'offer_type'),
    ('listings', 'purchase_conditions'),
    ('listings', 'year_built'),
    ('listings', 'address'),
    ('listings', 'lat'),
    ('listings', 'lng'),
    ('listings', 'views_count'),
    ('listings', 'is_premium'),
    ('listings', 'status'),
    ('listings', 'expires_at'),
    ('listings', 'created_at'),
    ('listings', 'updated_at'),
    ('listing_images', 'id'),
    ('listing_images', 'listing_id'),
    ('listing_images', 'url'),
    ('listing_images', 'order'),
    ('listing_images', 'is_cover'),
    ('favorites', 'id'),
    ('favorites', 'user_id'),
    ('favorites', 'listing_id'),
    ('favorites', 'created_at'),
    ('favorite_price_alerts', 'user_id'),
    ('favorite_price_alerts', 'listing_id'),
    ('favorite_price_alerts', 'last_notified_price'),
    ('favorite_price_alerts', 'last_notified_at'),
    ('saved_searches', 'id'),
    ('saved_searches', 'user_id'),
    ('saved_searches', 'name'),
    ('saved_searches', 'filters'),
    ('saved_searches', 'filters_hash'),
    ('saved_searches', 'notify_email'),
    ('saved_searches', 'notify_frequency'),
    ('saved_searches', 'last_checked_at'),
    ('saved_searches', 'last_viewed_at'),
    ('saved_searches', 'new_count'),
    ('saved_searches', 'updated_at'),
    ('saved_searches', 'created_at'),
    ('listing_reports', 'id'),
    ('listing_reports', 'listing_id'),
    ('listing_reports', 'user_id'),
    ('listing_reports', 'reason'),
    ('listing_reports', 'comment'),
    ('listing_reports', 'status'),
    ('listing_reports', 'created_at'),
    ('report_actions', 'id'),
    ('report_actions', 'report_id'),
    ('report_actions', 'actor_id'),
    ('report_actions', 'actor_role'),
    ('report_actions', 'old_status'),
    ('report_actions', 'new_status'),
    ('report_actions', 'notes'),
    ('report_actions', 'created_at'),
    ('support_tickets', 'id'),
    ('support_tickets', 'user_id'),
    ('support_tickets', 'subject'),
    ('support_tickets', 'status'),
    ('support_tickets', 'assigned_to'),
    ('support_tickets', 'created_at'),
    ('support_tickets', 'reported_user_id'),
    ('support_tickets', 'reason'),
    ('support_tickets', 'created_by_admin_id'),
    ('support_tickets', 'ticket_type'),
    ('support_tickets', 'updated_at'),
    ('support_ticket_events', 'id'),
    ('support_ticket_events', 'ticket_id'),
    ('support_ticket_events', 'actor_user_id'),
    ('support_ticket_events', 'actor_role'),
    ('support_ticket_events', 'event_type'),
    ('support_ticket_events', 'old_status'),
    ('support_ticket_events', 'new_status'),
    ('support_ticket_events', 'note'),
    ('support_ticket_events', 'created_at'),
    ('notifications', 'id'),
    ('notifications', 'user_id'),
    ('notifications', 'type'),
    ('notifications', 'title'),
    ('notifications', 'body'),
    ('notifications', 'link'),
    ('notifications', 'is_read'),
    ('notifications', 'created_at'),
    ('currencies', 'id'),
    ('currencies', 'code'),
    ('currencies', 'symbol'),
    ('currencies', 'name_sq'),
    ('currencies', 'name_en'),
    ('currencies', 'name_uk'),
    ('currencies', 'name_it'),
    ('currencies', 'is_active'),
    ('currencies', 'is_default'),
    ('currencies', 'decimals'),
    ('currencies', 'created_at'),
    ('currencies', 'updated_at'),
    ('exchange_providers', 'id'),
    ('exchange_providers', 'name'),
    ('exchange_providers', 'endpoint_url'),
    ('exchange_providers', 'api_key'),
    ('exchange_providers', 'refresh_interval_min'),
    ('exchange_providers', 'priority'),
    ('exchange_providers', 'mode'),
    ('exchange_providers', 'is_enabled'),
    ('exchange_providers', 'notes'),
    ('exchange_providers', 'created_at'),
    ('exchange_providers', 'updated_at'),
    ('property_types', 'id'),
    ('property_types', 'slug'),
    ('property_types', 'name_sq'),
    ('property_types', 'name_en'),
    ('property_types', 'name_uk'),
    ('property_types', 'name_it'),
    ('property_types', 'is_active'),
    ('property_types', 'sort_order'),
    ('property_types', 'created_at'),
    ('property_types', 'updated_at'),
    ('pages', 'id'),
    ('pages', 'title'),
    ('pages', 'slug'),
    ('pages', 'content'),
    ('pages', 'is_published'),
    ('pages', 'updated_by'),
    ('pages', 'updated_at'),
    ('site_settings', 'key'),
    ('site_settings', 'value'),
    ('site_settings', 'updated_at'),
    ('companies', 'id'),
    ('companies', 'name'),
    ('companies', 'logo_url'),
    ('companies', 'created_at'),
    ('collections', 'id'),
    ('collections', 'user_id'),
    ('collections', 'name'),
    ('collections', 'created_at'),
    ('collections', 'updated_at'),
    ('collection_items', 'collection_id'),
    ('collection_items', 'listing_id'),
    ('collection_items', 'created_at'),
    ('recently_viewed', 'id'),
    ('recently_viewed', 'user_id'),
    ('recently_viewed', 'listing_id'),
    ('recently_viewed', 'viewed_at'),
    ('role_permissions', 'role'),
    ('role_permissions', 'permission_key'),
    ('role_permissions', 'allowed'),
    ('role_permissions', 'updated_at'),
    ('contact_inquiries', 'id'),
    ('contact_inquiries', 'created_at'),
    ('contact_inquiries', 'topic'),
    ('contact_inquiries', 'custom_subject'),
    ('contact_inquiries', 'name'),
    ('contact_inquiries', 'email'),
    ('contact_inquiries', 'message'),
    ('contact_inquiries', 'target_mailbox'),
    ('contact_inquiries', 'requester_ip'),
    ('contact_inquiries', 'status'),
    ('contact_inquiries', 'handled_by'),
    ('contact_inquiries', 'handled_at'),
    ('contact_inquiries', 'reply_count'),
    ('contact_inquiry_replies', 'id'),
    ('contact_inquiry_replies', 'inquiry_id'),
    ('contact_inquiry_replies', 'replied_by'),
    ('contact_inquiry_replies', 'body'),
    ('contact_inquiry_replies', 'created_at')
)
SELECT
  ic.table_name,
  ic.column_name,
  'not in types' AS status
FROM information_schema.columns ic
LEFT JOIN expected e
  ON  e.table_name   = ic.table_name
  AND e.column_name  = ic.column_name
WHERE ic.table_schema = 'public'
  AND ic.table_name IN ('users', 'user_change_log', 'user_status_history', 'email_change_tokens', 'email_templates', 'locations', 'listings', 'listing_images', 'favorites', 'favorite_price_alerts', 'saved_searches', 'listing_reports', 'report_actions', 'support_tickets', 'support_ticket_events', 'notifications', 'currencies', 'exchange_providers', 'property_types', 'pages', 'site_settings', 'companies', 'collections', 'collection_items', 'recently_viewed', 'role_permissions')
  AND e.column_name IS NULL
ORDER BY ic.table_name, ic.column_name;
